### ISSUE TITLE
Build error, no node_modules directory.

### ISSUE THREAD

**Issue by nagolove** [euclidianAce/tree-sitter-teal#2]
I cloned repo and did `make` command.
```
gcc -fPIC -shared src/parser.c src/scanner.c -o parser.so
./node_modules/tree-sitter-cli/tree-sitter test
make: ./node_modules/tree-sitter-cli/tree-sitter: No such file or directory
make: *** [Makefile:8: test] Error 127
```
What is the error? I should install some nodejs modules by `npm`?

**Comment by euclidianAce** [comment]
I've changed the Makefile a little bit recently so now the default is that it just builds the parser. To run the tests it does assume that you have the `tree-sitter` cli in your `PATH` which can be installed through `npm`
