### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Suya1671** [euclidianAce/tree-sitter-teal#20]
When I try building this, I get an error

![image](https://user-images.githubusercontent.com/45307955/173197523-97f1b593-1641-468c-b412-f34d05640bd6.png)

This seems to be a volta error, which is caused by not having a node_modules folder

**Comment by Andre-LA** [comment]
I personally got it working here, I installed [tree-sitter-cli through cargo](https://crates.io/crates/tree-sitter-cli), I'm using `tree-sitter 0.20.8`, and commands like `generate`, `test` and `highlight` works.

Curiously `make` don't work for me though.
