### ISSUE TITLE
CI to bundle releases

### ISSUE THREAD

**Issue by euclidianAce** [euclidianAce/tree-sitter-teal#24]
My github actions knowledge is shoddy at best and my tree-sitter knowledge has atrophied so I'm not sure how people expect releases to be formatted.

**Comment by clason** [comment]
Ideally, a snapshot of the repo with all generated files (that are omitted in the repo) included, plus a wasm artifact. Semver is also expected (patch for fixes that don't affect queries; minor for new nodes that don't break queries; major for removed or renamed nodes that do break queries -- like the recent change to `string`).

**Comment by clason** [comment]
(And WASM parsers as first-tier targets means that not all stdlib functions can be used in scanners -- this is why building the parser now fails on macOS and friends: `is_ascii_whitespace` is not available.)
