### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [euclidianAce/tree-sitter-teal#26]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `Teal` (select `Tree-sitter-ebnf-generator-teal` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by euclidianAce** [comment]
The input EBNF seems to be relatively similar to the original `grammar.js` just with a different syntax and likely less functionality. I think an important distinction is that `grammar.js` can use javascript features such as mapping over lists of items to produce similar grammar rules like for `bin_op`. Additionally adding an extra tool (and language dependency) to generate the input of a code generator that is not yet stable in its features seems fragile.

If this could take the EBNF from the teal repo and generate a grammar then it _might_ be worth considering (maybe as a way of validating that the EBNF in the teal repo is correct). But it is already relatively easy to maintain this grammar as teal is unlikely to make any drastic changes to syntax.

Apologies, but I don't think I will be using this. Thank you for the suggestion.
