### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by barsoosayque** [euclidianAce/tree-sitter-teal#36]
As of now, tree-sitter-teal doesn't have any license, and so it's unclear how to properly integrate it in other projects (for example, [adding support for teal in helix](https://github.com/helix-editor/helix/pull/12081)). It would be nice to have a LICENSE for that, maybe the same MIT license that [teal itself has](https://github.com/teal-language/tl/blob/master/LICENSE) ?

**Comment by euclidianAce** [comment]
Apologies for the slow response. I've just added the license file in 3db6559, thanks for opening the issue.
